### PR TITLE
avm2: Properly make all classes an instance of `Class`.

### PR DESCRIPTION
**Pull request by kmeisthax**
You should be able to merge this into your PR in order to fix those tests. This ensures that all classes...

1. Have `Class.prototype` as their `__proto__`
2. Get all instance traits defined by `Class`.

### CODE REVIEW

**Comment by adrian17** [comment]
This fixes all ABC-defined classes and most builtin classes, except the three core ones Object, Class, Function - ones created with `ClassObject::from_builtin_class`. These are the awkward ones, as they need to be initialized out of order.
My failing test:
image

**Comment by kmeisthax** [comment]
@adrian17 I've added more code to ensure that all core classes are instances of `Class`, including `Class` itself. You should be able to merge this into your PR - in the meantime I'm going to review what you have.

An interesting behavior I discovered is that core class *prototypes* are also instances of their class. This breaks our current ES3 legacy support, because of...

1. Ruffle legacy from the era of lazy-init traits (easy enough to remove)
2. Bound methods on prototypes

Basically, `Object.hasOwnProperty` is a trait method, and you can access it from any object, including legacy ES3 class instances, through the prototype chain. This also bypasses method binding - in other words, `callproperty` needs to be able to get at unbound methods. I believe the easiest way to do this would be to lazily init bound methods (which conflicts with part 1 up above, but I can work around that...). Then, `callproperty` can grab the unbound versions off the prototype. This also means that I can't actually implement prototypes-are-instances until #5317 goes through, because that's where I put the call/get split.

**Review by adrian17 — APPROVED** [review]
LGTM, can merge, just one thing - do you wanna add a test for `Class` type check and coercion? Or would you rather do it in your later PRs?

**Comment by kmeisthax** [comment]
Done.

**Comment by adrian17** [comment]
> Also, does this technically mean that `Class` is a metaclass?

Didn't notice this one before :)
At least in Python, there is a very similar relationship between `object` and `type` with each being `isinstance` of another - and there it's just a side effect of everything being an object on the same rights; while metaclasses are an entirely separate concept.

**Comment by adrian17** [comment]
Thank you, will squash upon merging.

**Pull request merged**
